### ISSUE TITLE
error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO

### ISSUE THREAD

**Issue by trafficonese** [amrrs/coinmarketcapr#12]
It seems that all exported functions are broken and produce this error:

> Error in function (type, msg, asError = TRUE)  : 
>   error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

Apparently the error is triggered by the `RCurl` package. I looked at the `get_marketcap_ticker_all` code and made it work with the `curl` package. (Related to #10)

`data.frame(jsonlite::fromJSON(rawToChar(curl::curl_fetch_memory(paste0("https://api.coinmarketcap.com/v1/ticker/?convert=", "USD"))$content)))`

Are you willing to switch to `curl` entirely? If so, then I could make those changes and send a PR.

**Comment by amrrs** [comment]
Would you be interested in adding your name to the authors list?

**Comment by trafficonese** [comment]
I just openend a new PR #15.

Issue #10 can also be closed.

Thanks for the quick merge.
