### ISSUE TITLE
Critical: Package removed from CRAN

### ISSUE THREAD

**Issue by amrrs** [amrrs/coinmarketcapr#17]
Have to fix the exceptions to handle failures from API calls

**Comment by amrrs** [comment]
Currently fails like this - 

```
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <!--[if lt IE 7
                     (right here) ------^
```

**Comment by trafficonese** [comment]
The easiest solution for CRAN would be to skip all tests on CRAN.

Additionally I would add a response Check for old API calls aswell, to inform that too many requests were sent and the IP is temporarily banned.

**Comment by amrrs** [comment]
Thanks @trafficonese . I think it's necessary to have some tests. I need to check how others usually do these tests when we have to deal with APIs

**Comment by trafficonese** [comment]
Yes it's definitly a good idea to test, but tests would happen in Travis already. We could also test on appveyor. So I'm not sure if it's also necessary to test on CRAN.

But yes, if you find other packages that require an API and have good test coverage, it would be interesting to see how they do it, also if they expose API keys like I did in the tests. For more "delicate" packages I doubt they would publish their API keys so publicly :)

Could you check why the build is failing? It has something to do with the vignette. I also had some problems with it aswell and I'm not too experienced with vignettes.
It would also be nice to have another vignette, which treats the whole API topic in more depth, with the new function calls. Or should we pack everything in the "Getting Started" vignette?

**Comment by amrrs** [comment]
@trafficonese  Having a separate vignette is a better idea. When i tried to go through CRAN tests locally, Vignette took a lot of time. Need to see why it's. Worst case we can skip vignette. 

For testing, There's a concept called `mocking` 

https://blog.r-hub.io/2019/10/29/mocking/

Need to check this further!

**Comment by amrrs** [comment]
@trafficonese  Thanks so much again! We're back on CRAN

https://cran.r-project.org/web/packages/coinmarketcapr/index.html 

But Travis build is failing again :(
