### ISSUE TITLE
API

### ISSUE THREAD

**Issue by F041** [amrrs/coinmarketcapr#28]
library(coinmarketcapr)

#get the global market cap details and assign it to a dataframe
latest_marketcap <- get_global_marketcap('EUR')

‼ The old API is used when no 'apikey' is given. 
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML> <html lang="en-
                     (right here) ------^

**Comment by amrrs** [comment]
Hey, You've to get the API key from Coinmarketcap website.
