### ISSUE TITLE
Check if the plot_top_currencies() function is working

### ISSUE THREAD

**Issue by amrrs** [amrrs/coinmarketcapr#29]
There was a report that the plot function isn't working even when the API key is provided. Validate it!

**Comment by reyesmariana141** [comment]
Yes the plot function is not working

**Comment by amrrs** [comment]
Did you try with the API key?

**Comment by reyesmariana141** [comment]
devtools::install_github("amrrs/coinmarketcapr")
coinmarketcapr::setup('I put my APIU key here')
plot_top_currencies(currency = "USD", k = 5, bar_color = "grey")
Error in plot_top_currencies(currency = "USD", k = 5, bar_color = "grey",  : 
  unused argument (alist(API = ))

**Comment by amrrs** [comment]
I think the column names have changed from the api result, i need to fix this. Is this urgent for you?

**Comment by reyesmariana141** [comment]
If you have the time it would be of good help

**Comment by amrrs** [comment]
Do you have any deadline on when do you want this?

**Comment by reyesmariana141** [comment]
Probably before the month ends Thank you

**Comment by amrrs** [comment]
I updated the package. Can you try to install the latest package from github and try using plot?
```
install.packages("devtools")
devtools::install_github("amrrs/coinmarketcapr")
```

**Comment by reyesmariana141** [comment]
Thank you so much !

**Comment by amrrs** [comment]
@reyesmariana141 Did it work?

**Comment by reyesmariana141** [comment]
yes thank you
