### ISSUE TITLE
lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by mikepumpkineater** [amrrs/coinmarketcapr#30]
After installing the package, I get this error using the basic commands from the manual

```
library(coinmarketcapr)
latest_marketcap <- get_global_marketcap('EUR')
```

lexical error: invalid char in json text.
                                       <!DOCTYPE HTML> <html lang="en-
                     (right here) ------^

**Comment by KatlehoJordan** [comment]
I am also getting an error as of today:

Input:
`coinmarketcapr::get_crypto_listings(limit = 5000)`

Output:
`Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//IETF/
                     (right here) ------^`

**Comment by amrrs** [comment]
Did you try it with the API key?

**Comment by KatlehoJordan** [comment]
Yes. I have a private key that I use which used to work but stopped working.

I wrote up a workaround, so I can do my API calls to coinmarket cap without the coinmarketcapr library now.

**Comment by amrrs** [comment]
That's amazing. Good one

**Comment by KristenKehrer** [comment]
> I wrote up a workaround, so I can do my API calls to coinmarket cap without the coinmarketcapr library now.

I'm having this same issue.

**Comment by amrrs** [comment]
@KristenKehrer Did you try with the API Key?

**Comment by amrrs** [comment]
I'm closing this issue as it's been too long, feel free to open it again if your problem is unresolved
