### ISSUE TITLE
Something wrong with the JSON File

### ISSUE THREAD

**Issue by reyesmariana141** [amrrs/coinmarketcapr#32]
> latest_marketcap <- get_global_marketcap('EUR')
‼ The old API is used when no 'apikey' is given. 
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML> <html lang="en-
                     (right here) ------^

**Comment by amrrs** [comment]
You need to try with API key

**Comment by amrrs** [comment]
I'll close this issue given API key has to be used.
