### ISSUE TITLE
Show more than 100 coins

### ISSUE THREAD

**Issue by wsamuelw** [amrrs/coinmarketcapr#5]
Would be great to show more than 100 coins with this function get_marketcap_ticker_all()

**Comment by amrrs** [comment]
Hi @wsamuelw The dev version has been updated with your request. Please check:

`devtools::install_github('amrrs/coinmarketcapr')`

and share if it works!

**Comment by wsamuelw** [comment]
Awesome! Now, showing 1381 rows. Cheers

**Comment by amrrs** [comment]
Would you be okay to share - how or where are you using this?

**Comment by wsamuelw** [comment]
I will need to spend some time to see what I can do with the package.

**Comment by amrrs** [comment]
Oh, That's okay!
