### ISSUE TITLE
Move to API v2

### ISSUE THREAD

**Issue by amrrs** [amrrs/coinmarketcapr#9]
Public API Version 1 will be taken offline on November 30th, 2018. Please modify your application to use Version 2 prior to shutdown.
 
https://coinmarketcap.com/api/#endpoint_listings

**Comment by trafficonese** [comment]
The v1 API is still working or? Do you know, when it will be really shutdown?

Do you plan to update the package to support the new API? With both, free and paid services?

**Comment by amrrs** [comment]
The v1 API is still working, I thought it wouldn't that's the same thing related to #11  as i wanted to check if the data coming through is right after the API update. Didn't do either :(

**Comment by trafficonese** [comment]
Are you planning on upgrading the package to support the new API? I am willing to help in that process and also expand the current functions.

**Comment by trafficonese** [comment]
I am working on a rewrite to support both API versions in this fork: https://github.com/trafficonese/coinmarketcap_v2/tree/master/R

If you want, I would open a PR for it, when I'm done, but its more or less a complete rewrite of the package. Also the results including column names differ between the APIs.

I currently only have a Basic API, so I cannot test everything, but it should be possible to include all functionalities of the CCM-API. There is also a sandbox-URL but I wasnt able to get results from that there.

**Comment by amrrs** [comment]
@trafficonese I'm not sure if we have to cover the paid API without testing, Wouldn't it become a difficult thing for debugging if someone faces an issue?

**Comment by amrrs** [comment]
Moreover I'm just intrigued @trafficonese , how did your interest towards this package come in?

**Comment by trafficonese** [comment]
Indeed, I might get an API with more rights or get the sandbox runnning, than all requests can be fully tested.

Well, I am actually interested in building a crypto portfolio manager and/with a crypto bot in R and I was looking for packages to support those ideas ;)

Right now there's just the `crypto` package which really scrapes data from the website, but it is quite slow to get historical data. So I would prefer an API solution for that end.

**Comment by trafficonese** [comment]
Ah, I needed to create a new API key for the sandbox. I was trying to use my basic API key which didn't work.
So now I have a testing API key with "Professional" rights. With this one everything should be testable and I could also leave that key in the test script as its just a sandbox environment with an old dataset.

**Comment by amrrs** [comment]
> .

Really great to know this. I'm glad `coinmarketcapr` is getting a good contribution as part of this drive.

**Comment by amrrs** [comment]
> Well, I am actually interested in building a crypto portfolio manager and/with a crypto bot in R and I was looking for packages to support those ideas ;)
> 
> Right now there's just the `crypto` package which really scrapes data from the website, but it is quite slow to get historical data. So I would prefer an API solution for that end.

Really great to know this. I'm glad `coinmarketcapr` is getting a good contribution as part of this drive.

**Comment by trafficonese** [comment]
Short Update.
I am done with an initial rewrite to support the new API.
You can check it out [here ](https://github.com/trafficonese/coinmarketcap_v2).

In the test suite, I included 2 API Keys, a basic key and a professional sandbox key. I am not sure if this is a good idea, to publish them like that, but actually nothing bad can be done with them.

I think, now the whole API can be accessed.

Also the original functions should still work without setting up an API key, but they throw a warning which states that the old API is used.

If you like it and would like to include it, i would send a PR.

**Comment by amrrs** [comment]
@trafficonese  Did you get to check the tests and cran compatibility using `devtools::check()` bunch of things are failing it seems

```

── Test failures ──────────────────── testthat ────

> library(testthat)
> library(coinmarketcapr)
> 
> test_check("coinmarketcapr")
── 1. Error: The output dataframe Type is  (@test-f
lexical error: invalid char in json text.
                                       <!DOCTYPE html> <!--[if lt IE 7
                     (right here) ------^
Backtrace:
 1. testthat::expect_equal(class(get_global_marketcap("USD")), "data.frame")
 4. coinmarketcapr::get_global_marketcap("USD")
 6. jsonlite::fromJSON(...)
 7. jsonlite:::parse_and_simplify(...)
 8. jsonlite:::parseJSON(txt, bigint_as_char)
 9. jsonlite:::parse_string(txt, bigint_as_char)

── 2. Error: The output dataframe Type is  (@test-f
lexical error: invalid char in json text.
                                       <!DOCTYPE html> <!--[if lt IE 7
                     (right here) ------^
Backtrace:
 1. testthat::expect_equal(...)
 4. coinmarketcapr::get_marketcap_ticker_all("USD")
 6. jsonlite::fromJSON(...)
 7. jsonlite:::parse_and_simplify(...)
 8. jsonlite:::parseJSON(txt, bigint_as_char)
 9. jsonlite:::parse_string(txt, bigint_as_char)

── 3. Error: The output ggplot Type is  (@test-fun.
lexical error: invalid char in json text.
                                       <!DOCTYPE html> <!--[if lt IE 7
                     (right here) ------^
Backtrace:
  1. testthat::expect_true(is.ggplot(plot_top_currencies("USD")))
  5. coinmarketcapr::plot_top_currencies("USD")
  7. jsonlite::fromJSON(...)
  8. jsonlite:::parse_and_simplify(...)
  9. jsonlite:::parseJSON(txt, bigint_as_char)
 10. jsonlite:::parse_string(txt, bigint_as_char)

══ testthat results  ══════════════════════════════
[ OK: 0 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 3 ]
1. Error: The output dataframe Type is  (@test-fun.R#7) 
2. Error: The output dataframe Type is  (@test-fun.R#14) 
3. Error: The output ggplot Type is  (@test-fun.R#22) 

Error: testthat unit tests failed
Execution halted

2 errors ✖ | 1 warning ✖ | 0 notes ✔

```

**Comment by amrrs** [comment]
@trafficonese  looks like if we use `old_api` coinmarketcap is banning our IP

**Comment by trafficonese** [comment]
Yes, I got those errors aswell at some point.
This happens if the API is requested too often, then the IP gets a temporary ban.

I tried to replicate this the last time, to include some checks for that, but I didnt get a ban. I'll have to try harder getting banned :)
